name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

  workflow_dispatch:

defaults:
  run:
    working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install Dependencies
        run: dotnet restore blazor-basic-swa.sln
      - name: Build
        run: dotnet build blazor-basic-swa.sln --configuration Release --no-restore
